
import type { Product } from './types';

// This is now just the initial seed data.
// The app will use localStorage as the primary source of truth.
export const products: Product[] = [
  {
    id: 'ritter-sport-marzipan-1',
    name: 'Ritter Sport Marzipan Dark Chocolate, Fresh from Germany, Chocolate with Marzipan Filling, Ritter Sport Chocolates in Colorful Variety, 3.5 Ounce (Pack of 12)',
    price: 945,
    image: 'https://iili.io/fYK3fZN.jpg',
    imageHint: 'ritter sport marzipan chocolate',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'ritter-sport-kakao-mousse-2',
    name: 'Ritter Sport Kakao (Cocoa) Mousse Chocolate - Pack of 3',
    price: 945,
    image: 'https://iili.io/fYKB46B.png',
    imageHint: 'ritter sport kakao mousse chocolate',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'ritter-sport-milk-chocolate-3',
    name: 'Ritter Sport Milk Chocolate with Butter Biscuit, 3.5 oz',
    price: 945,
    image: 'https://iili.io/fYfKy0P.png',
    imageHint: 'ritter sport milk chocolate butter biscuit',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'mogu-mogu-pineapple-4',
    name: 'Mogu Mogu Juice with Nata De Coco, Pineapple',
    price: 350,
    image: 'https://iili.io/fYfjJVa.png',
    imageHint: 'mogu mogu juice pineapple nata de coco',
    category: 'Drinkable',
    isNew: true,
  },
  {
    id: 'pringles-cheesy-cheese-5',
    name: 'Pringles Cheesy Cheese Chips 165g',
    price: 945,
    image: 'https://iili.io/fYqlfxR.png',
    imageHint: 'pringles cheesy cheese chips',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'kurkure-naughty-tomato-6',
    name: 'Kurkure Naughty Tomato — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-naughty-tomato/600/600',
    imageHint: 'kurkure tomato',
    category: 'Snacks',
  },
  {
    id: 'kurkure-masala-munch-7',
    name: 'Kurkure Masala Munch — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-masala-munch/600/600',
    imageHint: 'kurkure masala',
    category: 'Snacks',
  },
  {
    id: 'kurkure-chutney-chaska-8',
    name: 'Kurkure Chutney Chaska — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-chutney-chaska/600/600',
    imageHint: 'kurkure chutney',
    category: 'Snacks',
  },
  {
    id: 'kurkure-chilli-chatka-9',
    name: 'Kurkure Chilli Chatka — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-chilli-chatka/600/600',
    imageHint: 'kurkure chilli',
    category: 'Snacks',
  },
  {
    id: 'lays-flamin-hot-10',
    name: "Lays Flamin' Hot — 34.5g",
    price: 75,
    image: 'https://picsum.photos/seed/lays-flamin-hot/600/600',
    imageHint: 'lays flamin hot',
    category: 'Snacks',
  },
  {
    id: 'lays-french-cheese-11',
    name: 'Lays French Cheese — 34.5g',
    price: 75,
    image: 'https://picsum.photos/seed/lays-french-cheese/600/600',
    imageHint: 'lays french cheese',
    category: 'Snacks',
  },
  {
    id: 'lays-classic-salted-12',
    name: 'Lays Classic Salted — 34.5g',
    price: 75,
    image: 'https://picsum.photos/seed/lays-classic-salted/600/600',
    imageHint: 'lays classic',
    category: 'Snacks',
  },
  {
    id: 'lays-yogurt-herb-13',
    name: 'Lays Yogurt & Herb — 34.5g',
    price: 75,
    image: 'https://picsum.photos/seed/lays-yogurt-herb/600/600',
    imageHint: 'lays yogurt herb',
    category: 'Snacks',
  },
  {
    id: 'slanty-cheese-flavor-14',
    name: 'Slanty Cheese Flavor — 20g',
    price: 35,
    image: 'https://picsum.photos/seed/slanty-cheese-flavor/600/600',
    imageHint: 'slanty cheese',
    category: 'Snacks',
  },
  {
    id: 'slanty-chilli-flavor-15',
    name: 'Slanty Chilli Flavor — 20g',
    price: 35,
    image: 'https://picsum.photos/seed/slanty-chilli-flavor/600/600',
    imageHint: 'slanty chilli',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-salad-16',
    name: 'Super Crisp Salad (Salted) — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-salad/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-masala-masti-17',
    name: 'Super Crisp Masala Masti — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-masala-masti/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-pizza-18',
    name: 'Super Crisp Pizza — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-pizza/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-bbq-19',
    name: 'Super Crisp BBQ — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-bbq/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-ketchup-20',
    name: 'Super Crisp Ketchup — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-ketchup/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-sour-cream-onion-21',
    name: 'Super Crisp Sour Cream & Onion — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-sour-cream-onion/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'wavy-maxx-sizzling-bbq-22',
    name: 'Wavy Maxx Sizzling BBQ — 25g',
    price: 50,
    image: 'https://picsum.photos/seed/wavy-maxx-sizzling-bbq/600/600',
    imageHint: 'wavy maxx',
    category: 'Snacks',
  },
  {
    id: 'wavy-maxx-creamy-onion-23',
    name: 'Wavy Maxx Creamy Onion — 25g',
    price: 50,
    image: 'https://picsum.photos/seed/wavy-maxx-creamy-onion/600/600',
    imageHint: 'wavy maxx',
    category: 'Snacks',
  },
  {
    id: 'biscolata-mood-chocolate-24',
    name: 'Biscolata Mood Chocolate — 100g',
    price: 399,
    image: 'https://picsum.photos/seed/biscolata-mood-chocolate/600/600',
    imageHint: 'biscolata chocolate',
    category: 'Biscuits',
  },
  {
    id: 'tuc-biscuit-25',
    name: 'Tuc Biscuit — 66g',
    price: 80,
    image: 'https://picsum.photos/seed/tuc-biscuit/600/600',
    imageHint: 'tuc biscuit',
    category: 'Biscuits',
  },
  {
    id: 'prince-biscuit-26',
    name: 'Prince Biscuit — 68g',
    price: 80,
    image: 'https://picsum.photos/seed/prince-biscuit/600/600',
    imageHint: 'prince biscuit',
    category: 'Biscuits',
  },
  {
    id: 'nido-milk-powder-27',
    name: 'Nido Full Cream Milk Powder — 400g',
    price: 450,
    image: 'https://picsum.photos/seed/nido-milk-powder/600/600',
    imageHint: 'nido milk powder',
    category: 'Dairy',
  },
  {
    id: 'olive-oil-28',
    name: 'Extra Virgin Olive Oil — 500ml',
    price: 850,
    image: 'https://picsum.photos/seed/olive-oil/600/600',
    imageHint: 'olive oil',
    category: 'Cooking Essentials',
  },
  {
    id: 'rice-basmati-29',
    name: 'Basmati Rice — 5kg',
    price: 1200,
    image: 'https://picsum.photos/seed/basmati-rice/600/600',
    imageHint: 'basmati rice',
    category: 'Grains & Rice',
  },
  {
    id: 'coca-cola-30',
    name: 'Coca Cola — 2.25L',
    price: 180,
    image: 'https://picsum.photos/seed/coca-cola/600/600',
    imageHint: 'coca cola',
    category: 'Beverages',
  },
  {
    id: 'dove-soap-31',
    name: 'Dove Beauty Bar Soap — 100g',
    price: 120,
    image: 'https://picsum.photos/seed/dove-soap/600/600',
    imageHint: 'dove soap',
    category: 'Personal Care',
  },
  {
    id: 'detergent-powder-32',
    name: 'Ariel Detergent Powder — 1kg',
    price: 450,
    image: 'https://picsum.photos/seed/ariel-detergent/600/600',
    imageHint: 'ariel detergent',
    category: 'Household',
  },
  {
    id: 'baby-diapers-33',
    name: 'Pampers Baby Diapers — Medium (56 count)',
    price: 1200,
    image: 'https://picsum.photos/seed/pampers-diapers/600/600',
    imageHint: 'pampers diapers',
    category: 'Baby Care',
  },
  {
    id: 'bread-34',
    name: 'Fresh White Bread — 500g',
    price: 80,
    image: 'https://picsum.photos/seed/white-bread/600/600',
    imageHint: 'white bread',
    category: 'Bakery',
  },
  {
    id: 'frozen-pizza-35',
    name: 'Frozen Pizza — 400g',
    price: 350,
    image: 'https://picsum.photos/seed/frozen-pizza/600/600',
    imageHint: 'frozen pizza',
    category: 'Frozen Foods',
  },
  {
    id: 'coffee-36',
    name: 'Instant Coffee — 100g',
    price: 250,
    image: 'https://picsum.photos/seed/instant-coffee/600/600',
    imageHint: 'instant coffee',
    category: 'Beverages',
  },
  {
    id: 'shampoo-37',
    name: 'Head & Shoulders Shampoo — 340ml',
    price: 380,
    image: 'https://picsum.photos/seed/head-shoulders/600/600',
    imageHint: 'head shoulders shampoo',
    category: 'Personal Care',
  },
  {
    id: 'toothpaste-38',
    name: 'Colgate Toothpaste — 100ml',
    price: 150,
    image: 'https://picsum.photos/seed/colgate-toothpaste/600/600',
    imageHint: 'colgate toothpaste',
    category: 'Personal Care',
  },
  {
    id: 'cleaning-spray-39',
    name: 'Multi-Surface Cleaner Spray — 500ml',
    price: 280,
    image: 'https://picsum.photos/seed/cleaning-spray/600/600',
    imageHint: 'cleaning spray',
    category: 'Household',
  },
  {
    id: 'baby-wipes-40',
    name: 'Baby Wipes — 80 sheets',
    price: 350,
    image: 'https://picsum.photos/seed/baby-wipes/600/600',
    imageHint: 'baby wipes',
    category: 'Baby Care',
  },
  {
    id: 'pasta-41',
    name: 'Italian Pasta — 500g',
    price: 220,
    image: 'https://picsum.photos/seed/italian-pasta/600/600',
    imageHint: 'italian pasta',
    category: 'Pasta & Noodles',
  },
  {
    id: 'tomato-sauce-42',
    name: 'Tomato Ketchup — 500g',
    price: 180,
    image: 'https://picsum.photos/seed/tomato-ketchup/600/600',
    imageHint: 'tomato ketchup',
    category: 'Condiments',
  },
  {
    id: 'tea-bags-43',
    name: 'Green Tea Bags — 25 count',
    price: 200,
    image: 'https://picsum.photos/seed/green-tea/600/600',
    imageHint: 'green tea bags',
    category: 'Beverages',
  },
  {
    id: 'honey-44',
    name: 'Pure Honey — 500g',
    price: 650,
    image: 'https://picsum.photos/seed/pure-honey/600/600',
    imageHint: 'pure honey',
    category: 'Condiments',
  },
  {
    id: 'tissues-45',
    name: 'Facial Tissues — 200 sheets',
    price: 120,
    image: 'https://picsum.photos/seed/facial-tissues/600/600',
    imageHint: 'facial tissues',
    category: 'Household',
  },
];

export const bestSellers: Product[] = [];
